name: train_de_mots
description: Jeu de mots pour animer des soirÃ©es entre amis sur Twitch
publish_to: 'none' 
version: 0.3.3+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  diacritic: ^0.1.4
  twitch_manager:
  collection: ^1.17.2
  just_audio: ^0.10.5
  just_audio_mpv: ^0.1.7
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.2.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  url_launcher: ^6.2.5
  http: ^1.2.1
  mutex: ^3.1.0
  logging: ^1.2.0
  common: 
    path: ../common
  vector_math: ^2.1.4
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  twitch_manager:
    path: ../common/plugins/twitch_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/youtube_logo.png