name: train_de_mots
description: Jeu de mots pour animer des soirÃ©es entre amis sur Twitch
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  diacritic: ^0.1.4
  twitch_manager:
    path: ./plugins/twitch_manager
  collection: ^1.17.2
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.2
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.2.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.15.5
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_screen.png
    - assets/images/parchment.png

    - assets/sounds/GameStarted.mp3
    - assets/sounds/LettersScrambling.mp3
    - assets/sounds/SolutionFound.mp3
    - assets/sounds/BestSolutionFound.mp3
    - assets/sounds/TelegramReceived.mp3
    - assets/sounds/TheSwindler.mp3
    - assets/sounds/TrainReachedStation.mp3
    - assets/sounds/RoundIsOver.mp3
