name: common
description: Common things to share between the EBS server, the App and the Frontend
version: 1.0.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  shared_preferences: ^2.2.0
  collection: ^1.18.0
  diacritic: ^0.1.4
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/train.png
    - assets/images/parchment.png

    - assets/images/treasure_hunt/blueberries.png
    - assets/images/treasure_hunt/grass.png
    - assets/images/treasure_hunt/open_grass.png

    - assets/images/blueberry_war/blueberries.png

    - assets/images/track_fix/grass.png
    - assets/images/track_fix/open_grass.png

    - assets/sounds/BestSolutionFound.mp3
    - assets/sounds/GameStarted.mp3
    - assets/sounds/GoldenSolutionAppeared.mp3
    - assets/sounds/LettersScrambling.mp3
    - assets/sounds/RoundIsOver.mp3
    - assets/sounds/SolutionFound.mp3
    - assets/sounds/SolutionStolen.mp3
    - assets/sounds/NewBoostGranted.mp3
    - assets/sounds/TelegramReceived.mp3
    - assets/sounds/TheSwindler.mp3
    - assets/sounds/TrainLostStation.mp3
    - assets/sounds/TrainReachedStation.mp3
    - assets/sounds/Fireworks1.mp3
    - assets/sounds/Fireworks2.mp3
    - assets/sounds/Fireworks3.mp3
    - assets/sounds/Fireworks4.mp3
    - assets/sounds/Fireworks5.mp3
    - assets/sounds/Fireworks6.mp3
    - assets/sounds/TheBigHeist.mp3
    - assets/sounds/BigHeistSuccess.mp3
    - assets/sounds/BigHeistFailed.mp3
    - assets/sounds/ChangingLane.mp3

    - assets/sounds/treasure_hunt/picking_treasure.mp3
    - assets/sounds/treasure_hunt/pluck_grass1.mp3 
    - assets/sounds/treasure_hunt/pluck_grass2.mp3 
    - assets/sounds/treasure_hunt/pluck_grass3.mp3
    - assets/sounds/treasure_hunt/pluck_grass4.mp3 

    - assets/sounds/blueberry_war/letter_hit.mp3
    - assets/sounds/blueberry_war/letter_knock.mp3

  fonts:
    - family: BaskervvilleSC
      fonts:
        - asset: assets/fonts/BaskervvilleSC/BaskervvilleSC-Regular.ttf
    - family: MedievalSharp
      fonts:
        - asset: assets/fonts/MedievalSharp/MedievalSharp-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto.woff2  
